### ISSUE TITLE
Дефект при открытии страницы zkSharding

### ISSUE THREAD

**Issue by ukorvl** [NilFoundation/nil.foundation#100]
https://github.com/NilFoundation/nil.foundation/assets/71327746/70a626a6-83fe-4428-8858-222391f6f5e2

Иногда при открытии страницы zkSharding проскакивает изображение иконки или кусок какой-то анимации в виде большой стрелки. Подробнее см. на видео.

## DoD
При открытии страницы сразу отображается черный фон и паттерн, без скачков кусочков разметки и лишних элементов.

**Comment by DariaLobanova** [comment]
@ukorvl @KlonD90 Проговорили в чате, что на проде баг не воспроизводится. Можете, пожалуйста, провалидировать актуальность issue и закрыть его, если больше неактуален?
