### ISSUE TITLE
Bug:Update the Vitalik's Blog Link in zkSharding Blog

### ISSUE THREAD

**Issue by HAPPYS1NGH** [NilFoundation/nil.foundation#171]
The blog post zkSharding [here](https://nil.foundation/blog/post/nil_zkSharding) in
### 4. Functionality
`[A Type-1 zkEVM](https://vitalik.ca/general/2022/08/04/zkevm.html), fully EVM bytecode-equivalent zkEVM compiled via zkLLVM.`

The Type 1 zkEVM link needs to be updated to https://vitalik.eth.limo/general/2022/08/04/zkevm.html.

Here is the image - 
<img width="1440" alt="Screenshot 2024-02-17 at 8 09 55 PM" src="https://github.com/NilFoundation/nil.foundation/assets/92804770/5e48a728-b684-4db7-add8-d04f26104810">

**Comment by nemothenoone** [comment]
@HAPPYS1NGH Thanks a lot for noticing this! Fixed!
