### ISSUE TITLE
Global site updates using UI-Kit

### ISSUE THREAD

**Issue by KlonD90** [NilFoundation/nil.foundation#67]
Here is a list for modernizing thing globally

1. Using fonts from ui-kit (it should work automatically with paragraph 3 here)
2. Using Web button component for action button
3. Using Typography components instead of custom one in every text block (mapping will be lately on figma design files)
4. Change color scheme using colors from ui-kit : FFFFFFF to gray50, 909090 to gray600, next mapping will be provided lately, also if color of something already presented in UI-kit should be used from it
5. Using Toggle Button component for tags instead of custom one (related to blogs/research pages) First, create Toggle button and Toggle buttons components in ui-kit https://github.com/NilFoundation/ui-kit/issues/171
6. New navigation bar component that will use UI-Kit components for it instead of old one (design will be lately)

**Comment by ukorvl** [comment]
Actually, i think we should not include to ui-kit components which will be used only in the website.
