### ISSUE TITLE
Удаление анимации паттернов и обновление то как выглядит их состояние

### ISSUE THREAD

**Issue by KlonD90** [NilFoundation/nil.foundation#69]
**Предупреждение**: Подразумевается, что эта задача выполняется после [изменения шрифтов на сайте](https://github.com/NilFoundation/nil.foundation/issues/71), чтобы иметь более четкое представление.

Нужно будет удалить анимации с сайта исключая 2 случая: интро в proofmarket page, интро в zkklvm page. При этом стоит уважать `prefers-reduced-motion` и у нас уже есть соотвествующий хук и если у пользователся включена эта галка то в этом случае их тоже не проигрывать, а показывать как отображено на макете.

Все остальные анимации должны быть удалены а их состояние должно быть приведено в соотвествие с макетами.

Макет: https://www.figma.com/file/9IKNrBtLd7mkDHnkcVBa1b/Site?node-id=235%3A54525&mode=dev

Напомню что в случае аниаций действует та же логика что и при тексте. Макеты делаются из расширения 1440 пикселей ширины соответственно позиции должны быть тянущимися и тоже делатся относительно этого момента. (Подробнее описано в введение в типографику https://github.com/NilFoundation/nil.foundation/issues/71 )

## DoD

Паттерны выглядят согласно макетам

**Comment by ukorvl** [comment]
@DariaLobanova да, все верно. В футере и при скролле не должно быть анимаций. Остается только анимация при открытии страницы.
