### ISSUE TITLE
WebButton component

### ISSUE THREAD

**Issue by KlonD90** [NilFoundation/nil.foundation#70]
Макет:
https://www.figma.com/file/9IKNrBtLd7mkDHnkcVBa1b/Site?node-id=138%3A40806&mode=dev - WebButton component should be implemented with this api:

```ts
type WebButtonProps = {
  children?: string,
  href?: string,
  onClick:? (event: MouseEvent) => void,
  size?: 's' | 'l' // default 's'
  disabled?: boolean
}
```

Его нужно будет положить в /site/src/components/common/WebButton

Поведение описано в макете.

## Ожидания

Ожидается цвета в компоненте будут вынесены в colors.scss с соответствующим названием.

<img width="285" alt="image" src="https://github.com/NilFoundation/nil.foundation/assets/790299/0c39f3f7-bc66-4d97-ae2f-11e8f4708f14">

То есть если gray200 то в colors.scss должен появиться gray200: который идет в этот цвет, чтобы в последствие мы могли черзе него манипулировать палитрой.
Также

## DoD

Сделан компонент с соотвествующим API готовый к использованию на сайте.

**Comment by ukorvl** [comment]
should be implemented with next api >
what does that mean?

**Comment by ukorvl** [comment]
Done by #82
