### ISSUE TITLE
Создание компонента Card

### ISSUE THREAD

**Issue by KlonD90** [NilFoundation/nil.foundation#73]
Компонент Card будет использоваться в качестве интерактивного элемента на сайте - кликабельная карточка.

## Описание

Макет: https://www.figma.com/file/9IKNrBtLd7mkDHnkcVBa1b/Site?node-id=235%3A54312&mode=dev

В макете описаны 3 состояния: Default, Hover, Focus.

Ожидаемое API компонента:

```ts
type CardProps = {
children?: ReactNode,
href?: string,
onClick?: (e: MouseEvent) => void
className?: string
}
```

Подразумевается что содержимое карточки будет задаваться через children и также помогать должен className.

## Ожидания

Цвета должны использоваться в соотвествие с их названиями из colors.scss если такого цвета нету то он должен добавляться туда и использоваться в дальнейшем оттуда. Также компонент должен быть достаточно гибким чтобы смочь в последствие быть использован для карточек с 2мя колонками внутри так и с 1й и с разным расстояниям компонентов внутри себя.

## DoD 

Создан компонент Card и он соотвествует макетам.

**Comment by ukorvl** [comment]
Done by #81
