### ISSUE TITLE
Использование ToggleButton

### ISSUE THREAD

**Issue by KlonD90** [NilFoundation/nil.foundation#77]
Компонент ToggleButton должен быть использован на сайте заместо тэгов в блогах и в research'ах.

1. https://nil.foundation/blog - внутри главной блога слева
2. https://nil.foundation/blog/category/announcement - внутри страницы категории слева
3. https://nil.foundation/blog/tag/about - внутри страницы тэга слева
4. https://nil.foundation/blog/post/introduction-post - внутри отдельного поста сверху
5. https://nil.foundation/research - ресерчи слева
6. https://nil.foundation/research/tag/dbms - по тэгу ресерча слева

## DoD

В этих местах в соотвествие с макетами используются ToggleButton вместо тэгов.

**Comment by Chipi007** [comment]
Вижу, что в макетах еще в самой карточке ресерча используется ToggleButton, но в требованиях выше этой задачи нет. Если все-таки нужно поменять и в карточке, дайте знать - поменяем)
